name: Dev - Deploy to Heroku
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_JWT_TOKEN_SECRET: ${{ secrets.JWT_TOKEN_SECRET }}
          envkey_MONGODB_URI: ${{ secrets.MONGODB_URI }}
          envkey_WELCOME_MESSAGE: ${{ secrets.WELCOME_MESSAGE }}

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'autonomo-api-dev'
          heroku_email: 'me@pabloibanez.com'
          usedocker: true
