name: Prod - Deploy to AWS
on: workflow_dispatch

jobs:
  deploy_prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Create env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          envkey_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          envkey_AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
          envkey_JWT_TOKEN_SECRET: ${{ secrets.JWT_TOKEN_SECRET }}
          envkey_MONGODB_URI: ${{ secrets.MONGODB_URI }}
          envkey_WELCOME_MESSAGE: ${{ secrets.WELCOME_MESSAGE }}

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: autonomo.api
          environment_name: autonomo-api-prod
          version_label: autonomo-api-prod-${{ github.sha }}
          region: eu-west-2
          deployment_package: deploy.zip
