name: Dev - Deploy to AWS
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Create env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          envkey_AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          envkey_AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          envkey_AUTH0_JWKS_URI: ${{ secrets.AUTH0_JWKS_URI }}
          envkey_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          envkey_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          envkey_MONGODB_URI: ${{ secrets.MONGODB_URI }}
          envkey_WELCOME_MESSAGE: ${{ secrets.WELCOME_MESSAGE }}

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: autonomo.api
          environment_name: autonomo-api-dev
          version_label: autonomo-api-dev-${{ github.sha }}
          region: eu-west-1
          deployment_package: deploy.zip
